# Generated by Django 4.0.5 on 2022-06-17 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HoodApp', '0002_neighbourhood_profile_post_neighbourhood_admin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
