# Generated by Django 4.0.5 on 2022-06-18 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HoodApp', '0005_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='prof_photo',
            new_name='profile_photo',
        ),
    ]
